/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheAvatarUploadBox: typeof import('./src/components/TheAvatarUploadBox.vue')['default']
    TheCalendarPanel: typeof import('./src/components/TheCalendarPanel.vue')['default']
    TheCheckboxGroup: typeof import('./src/components/TheCheckboxGroup.vue')['default']
    TheDropDown: typeof import('./src/components/TheDropDown.vue')['default']
    TheEmotionPieChart: typeof import('./src/components/TheEmotionPieChart.vue')['default']
    TheEventBarChart: typeof import('./src/components/TheEventBarChart.vue')['default']
    TheForceDirectedGraph: typeof import('./src/components/TheForceDirectedGraph.vue')['default']
    TheInputBox: typeof import('./src/components/TheInputBox.vue')['default']
    TheLogo: typeof import('./src/components/TheLogo.vue')['default']
    ThePanelHeader: typeof import('./src/components/ThePanelHeader.vue')['default']
    TheReasonDisplayPanel: typeof import('./src/components/TheReasonDisplayPanel.vue')['default']
    TheRoleBox: typeof import('./src/components/TheRoleBox.vue')['default']
    TheRoleDisplayCreatePanel: typeof import('./src/components/TheRoleDisplayCreatePanel.vue')['default']
    TheRoleInformationDisplayBox: typeof import('./src/components/TheRoleInformationDisplayBox.vue')['default']
    TheRoleSelectPanel: typeof import('./src/components/TheRoleSelectPanel.vue')['default']
    TheSearchWeibo: typeof import('./src/components/TheSearchWeibo.vue')['default']
    TheTimeControl: typeof import('./src/components/TheTimeControl.vue')['default']
    TheTimeControlPanel: typeof import('./src/components/TheTimeControlPanel.vue')['default']
    TheTimeline: typeof import('./src/components/TheTimeline.vue')['default']
    TheTimeLinePanel: typeof import('./src/components/TheTimeLinePanel.vue')['default']
    TheTwitterBox: typeof import('./src/components/TheTwitterBox.vue')['default']
    TheTwitterPanel: typeof import('./src/components/TheTwitterPanel.vue')['default']
    TheVisualAnalysisPanel: typeof import('./src/components/TheVisualAnalysisPanel.vue')['default']
    TheWeiboBox: typeof import('./src/components/TheWeiboBox.vue')['default']
    TheWeiboPanel: typeof import('./src/components/TheWeiboPanel.vue')['default']
  }
}
